- hosts: terraform-ansible
  tasks: 
  - name: criando o arquivo index
    copy: 
      dest: /home/azureuser/index.html
      content: <h1>Hello World. Feito com terraform e ansible.</h1>
  - name: criando o servidor
    shell: "nohup busybox httpd -f -p 8080 &"