- hosts: terraform-ansible
  tasks: 
  - name: instalando nginx e virtualenv
    apt: 
      pkg: 
      - nginx
      - virtualenv
      update_cache: yes
    become: yes
  - name: instalando Django e Django rest na venv.
    pip:
      virtualenv: ~/tcc/venv
      name: 
        - django
        - djangorestframework